### ISSUE TITLE
@v1 does not working

### ISSUE THREAD

**Issue by powerman** [ast-grep/action#38]
It's common use case to import actions using major version, i.e. `@v1` instead of `@v1.5` or `@latest` and let dependabot bother about next major version release.
![изображение](https://github.com/ast-grep/action/assets/1354301/dd17c648-56dc-4b35-9055-2cef4ac69578)

Actually it's first time I see an error like this - I believed when you've tag like `v1.5` then Github will automatically make `v1` work too. Maybe to make this work you need semver tags like `v1.5.0`? Or in case this repo does not follow semver then it probably should be noted in README and then requiring concrete version like `v1.5` is valid workflow.

**Comment by HerringtonDarkholme** [comment]
I have released a new one https://github.com/ast-grep/action/tree/v1.5.0

Please let me know if it works

**Comment by powerman** [comment]
No, it does not work. :disappointed: https://github.com/powerman/config.nvim/actions/runs/9748589942/job/26903884867

**Comment by HerringtonDarkholme** [comment]
<img width="458" alt="image" src="https://github.com/ast-grep/action/assets/2883231/d3d93ad5-dec5-4f95-91d5-8d52f6090423">

I checked `actions/checkout` repo and it looks like the v1 tag is released manually.

**Comment by HerringtonDarkholme** [comment]
I also created a v1 tag and releasse

**Comment by powerman** [comment]
Thanks, it works now!

P.S. Can't believe all actions authors are manually moving v1 tag on each release… this just doesn't makes sense. Not to say tags are supposed to be static.

**Comment by HerringtonDarkholme** [comment]
I will create an auto release github action in the future to automate action release.

Closing this in favor of https://github.com/ast-grep/action/issues/39 now
